// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: pkg/grpc/services.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SummonerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameName      string                 `protobuf:"bytes,1,opt,name=gameName,proto3" json:"gameName,omitempty"`
	TagLine       string                 `protobuf:"bytes,2,opt,name=tagLine,proto3" json:"tagLine,omitempty"`
	Region        string                 `protobuf:"bytes,3,opt,name=region,proto3" json:"region,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SummonerRequest) Reset() {
	*x = SummonerRequest{}
	mi := &file_pkg_grpc_services_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SummonerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SummonerRequest) ProtoMessage() {}

func (x *SummonerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_services_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SummonerRequest.ProtoReflect.Descriptor instead.
func (*SummonerRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_services_proto_rawDescGZIP(), []int{0}
}

func (x *SummonerRequest) GetGameName() string {
	if x != nil {
		return x.GameName
	}
	return ""
}

func (x *SummonerRequest) GetTagLine() string {
	if x != nil {
		return x.TagLine
	}
	return ""
}

func (x *SummonerRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

// Fetched summoner data.
type Summoner struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Puuid         string                 `protobuf:"bytes,1,opt,name=puuid,proto3" json:"puuid,omitempty"`
	GameName      string                 `protobuf:"bytes,2,opt,name=gameName,proto3" json:"gameName,omitempty"`
	TagLine       string                 `protobuf:"bytes,3,opt,name=tagLine,proto3" json:"tagLine,omitempty"`
	Region        string                 `protobuf:"bytes,4,opt,name=region,proto3" json:"region,omitempty"`
	SummonerLevel int32                  `protobuf:"varint,5,opt,name=summonerLevel,proto3" json:"summonerLevel,omitempty"`
	ProfileIconId int32                  `protobuf:"varint,6,opt,name=profileIconId,proto3" json:"profileIconId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Summoner) Reset() {
	*x = Summoner{}
	mi := &file_pkg_grpc_services_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Summoner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Summoner) ProtoMessage() {}

func (x *Summoner) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_services_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Summoner.ProtoReflect.Descriptor instead.
func (*Summoner) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_services_proto_rawDescGZIP(), []int{1}
}

func (x *Summoner) GetPuuid() string {
	if x != nil {
		return x.Puuid
	}
	return ""
}

func (x *Summoner) GetGameName() string {
	if x != nil {
		return x.GameName
	}
	return ""
}

func (x *Summoner) GetTagLine() string {
	if x != nil {
		return x.TagLine
	}
	return ""
}

func (x *Summoner) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *Summoner) GetSummonerLevel() int32 {
	if x != nil {
		return x.SummonerLevel
	}
	return 0
}

func (x *Summoner) GetProfileIconId() int32 {
	if x != nil {
		return x.ProfileIconId
	}
	return 0
}

var File_pkg_grpc_services_proto protoreflect.FileDescriptor

const file_pkg_grpc_services_proto_rawDesc = "" +
	"\n" +
	"\x17pkg/grpc/services.proto\x12\x04grpc\"_\n" +
	"\x0fSummonerRequest\x12\x1a\n" +
	"\bgameName\x18\x01 \x01(\tR\bgameName\x12\x18\n" +
	"\atagLine\x18\x02 \x01(\tR\atagLine\x12\x16\n" +
	"\x06region\x18\x03 \x01(\tR\x06region\"\xba\x01\n" +
	"\bSummoner\x12\x14\n" +
	"\x05puuid\x18\x01 \x01(\tR\x05puuid\x12\x1a\n" +
	"\bgameName\x18\x02 \x01(\tR\bgameName\x12\x18\n" +
	"\atagLine\x18\x03 \x01(\tR\atagLine\x12\x16\n" +
	"\x06region\x18\x04 \x01(\tR\x06region\x12$\n" +
	"\rsummonerLevel\x18\x05 \x01(\x05R\rsummonerLevel\x12$\n" +
	"\rprofileIconId\x18\x06 \x01(\x05R\rprofileIconId2E\n" +
	"\aService\x12:\n" +
	"\x0fGetSummonerData\x12\x15.grpc.SummonerRequest\x1a\x0e.grpc.Summoner\"\x00B\x13Z\x11goleague/pkg/grpcb\x06proto3"

var (
	file_pkg_grpc_services_proto_rawDescOnce sync.Once
	file_pkg_grpc_services_proto_rawDescData []byte
)

func file_pkg_grpc_services_proto_rawDescGZIP() []byte {
	file_pkg_grpc_services_proto_rawDescOnce.Do(func() {
		file_pkg_grpc_services_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_grpc_services_proto_rawDesc), len(file_pkg_grpc_services_proto_rawDesc)))
	})
	return file_pkg_grpc_services_proto_rawDescData
}

var file_pkg_grpc_services_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_grpc_services_proto_goTypes = []any{
	(*SummonerRequest)(nil), // 0: grpc.SummonerRequest
	(*Summoner)(nil),        // 1: grpc.Summoner
}
var file_pkg_grpc_services_proto_depIdxs = []int32{
	0, // 0: grpc.Service.GetSummonerData:input_type -> grpc.SummonerRequest
	1, // 1: grpc.Service.GetSummonerData:output_type -> grpc.Summoner
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_grpc_services_proto_init() }
func file_pkg_grpc_services_proto_init() {
	if File_pkg_grpc_services_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_grpc_services_proto_rawDesc), len(file_pkg_grpc_services_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_grpc_services_proto_goTypes,
		DependencyIndexes: file_pkg_grpc_services_proto_depIdxs,
		MessageInfos:      file_pkg_grpc_services_proto_msgTypes,
	}.Build()
	File_pkg_grpc_services_proto = out.File
	file_pkg_grpc_services_proto_goTypes = nil
	file_pkg_grpc_services_proto_depIdxs = nil
}
